spring:
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 5000
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/in_show_video?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
mybatis:
  type-aliases-package: com.InShow.video.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.InShow.video.utils.MyMapper
  not-empty: false
  identity: MYSQL
restart:
  include:
    mapper: /mapper-[\\w-\\.]+jar
    pagehelper: /pagehelper-[\\w-\\.]+jar
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  tomcat:
    uri-encoding: utf-8
com:
  Eriyuer:
    mysql:
      url: jdbc:mysql://localhost:3306/in_show_video
      driver: com.mysql.jdbc.Driver
      username: root
      password: 123456